#!/bin/bash
# Setup script for Google Maps API integration

echo "🗺️ Google Maps Setup Helper"
echo "================================"
echo ""
echo "To use the enhanced property form with Google Maps integration, follow these steps:"
echo ""
echo "1️⃣  Get your Google Maps API Key:"
echo "   - Visit: https://console.cloud.google.com/"
echo "   - Create a new project"
echo "   - Enable these APIs:"
echo "     • Maps JavaScript API"
echo "     • Places API"
echo "     • Geocoding API"
echo "   - Create an API key (Credentials → API Key)"
echo "   - Restrict to HTTP referrers (add localhost:3000 for dev)"
echo ""
echo "2️⃣  Add to .env.local:"
echo "   NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=your_api_key_here"
echo ""
echo "3️⃣  Update app/layout.tsx with:"
echo "   import Script from 'next/script';"
echo ""
echo "   <Script"
echo "     src={\`https://maps.googleapis.com/maps/api/js?key=\${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&libraries=places,geocoding\`}"
echo "     strategy='lazyOnload'"
echo "   />"
echo ""
echo "4️⃣  Restart your development server"
echo ""
echo "✅ Features enabled:"
echo "   - Nigerian states/cities dropdown (36 states + FCT)"
echo "   - Google Maps with search autocomplete"
echo "   - Drag-and-drop location marker"
echo "   - Click-to-set location on map"
echo "   - Automatic geocoding/address validation"
echo "   - Coordinates capture (latitude/longitude)"
echo ""
echo "📚 For detailed setup, see: GOOGLE_MAPS_SETUP.md"
echo "📝 For changes summary, see: PROPERTY_FORM_CHANGES.md"
echo ""
